prometheus-community/postgres_exporter

README.md, postgres_exporter.go
Added metrics for locks, pg_stat_replication and pg_stat_activity.
Added support to be able to collect metrics from more complex queries.
Added guide in README.md if you want to run as non-superuser.
=> Added metrics for locks, pg_stat_replication and pg_stat_activity

postgres_exporter.go
I have a PostgreSQL master with multiple replication slaves, which all come from the same source IP and have the same state usually.
Currently this results in the following output from postgres_exporter:
pg_stat_replication_pg_xlog_location_diff{client_addr="192.168.2.4",state="streaming"} NaN
pg_stat_replication_pg_xlog_location_diff{client_addr="192.168.2.4",state="streaming"} 48
and Prometheus only stores the first ("NaN") value. I added the application_name label to get Prometheus  to store both results.
=> Added application_name label to pg_xlog_location_diff gauge

.travis.yml, Makefile, postgres_exporter.go, tests/test-smoke
This simply pulls and runs postgres against a number of versions and checks
that we can successfully connect to it.
This currently throws a bunch of errors that are "normal", so we'll need to see about filtering them in the future.
=> Add docker based integration test suite.

postgres_exporter.go
it appears that the SHOW queries were returning the "string" type
First go code I ever wrote...
fixes https://github.com/wrouesnel/postgres_exporter/issues/15
=> Parse strings to floats

postgres_exporter.go
When querying postgres `pg_runtime_variable`, postgres might return -1
for `max_standby_archive_delay` and `max_standby_streaming_delay`
=> Handle `pg_runtime_variable` return values

.travis.yml, Dockerfile, Makefile
Docker 1.12 completely broke setting entrypoints on import, so we need to
switch to using an actual Dockerfile.
Also bump the pipeline to use Go 1.7.
=> Fix docker build steps.

postgres_exporter.go, queries.yaml, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go, vendor/vendor.json
Hi @wrouesnel ,
This PR adds support for custom queries in an external YAML file.
SHOW variables are not supported yet.
It should help close #1 .
I've deployed it yesterday and we're successfully getting metrics from our 54 Postgres replicas.
=> Feature queries from file

Makefile
Closes #19 (which doesn't build because we changed to using a Dockerfile).
=> Make the makefile less Linux specific

postgres_exporter.go
On a Debian + PostgreSQL 9.4 system I had a hard time getting the
exporter to work. It looks like I was running into some authentication
issues that weren't logged by sql.Open(), but by sql.DB.QueryRow().
This change extends the warning generated by the call to
checkMapVersions() to also print the error message generated by
sql.DB.QueryRow().
=> Properly print the SQL server error string in the log message.

Makefile, postgres_exporter.go
Made some changes so that the log messages are clearer when one have messed up the connection string. 
Fixed building of the container on a non linux native machine (e.g. Mac)
=> Improved error message

README.md
While many pronounce it as 'post-GRES', the spelling is 'PostgreSQL' with two 's'.
https://www.postgresql.org/about/press/faq/
=> Make references to PostgreSQL consistent

.travis.yml
I am interested in the postgres_exporter releases built with any Go > 1.7.0 since that should fix the issue https://github.com/golang/go/issues/16739 in Go.
=> Use latest minor version of Go 1.7

pg_setting.go, pg_setting_test.go
=> Handle pg_settings names with '.'

postgres_exporter.go
Fixes wrouesnel/postgres_exporter#67.
=> Add CLI flag to return version info

postgres_exporter.go
https://github.com/wrouesnel/postgres_exporter/issues/52
=> Ignore functions that cannot be executed during recovery.

README.md
* PostgreSQL name was misspelled in 53b9d9cea7de0d4ae4194e0e52ea2ca10911979b
* If the deployer role is not superuser (which is the case in AWS RDS,
for example), we need to grant it access to postgres_exporter role
before we can create a schema with AUTHORIZATION postgres_exporter.
=> Fix Postgres name + optionally grant postgres_exporter role to deployer role

.travis.yml, pg_setting.go, pg_setting_test.go
We are missing the 16kB unit size, which triggers a panic (by design).
Resolves #101
=> Resolve issue 101

Makefile, postgres_exporter.go, postgres_exporter_integration_test_script, tests/test-smoke
Add Postgres 10 as a smoke-tested version and add explicit support.
Closes #119 #111 #91
TODOs: some of the new time metrics would be worthwhile to parse, but will be handled in a future PR.
=> Postgres 10 support

postgres_exporter.go, postgres_exporter_integration_test.go
When using queries.yaml, extra columns in the output would be detected as
unknown metrics (correctly) but the labels in the current mapping would not be
applied to the output.
This explains the rash of crashes due to inconsistent label cardinality. The
specific creation is when the name given to a column does not match the mapping
you intended, and so the metric shows up as unknown.
Closes #98
=> Fix panic due to inconsistent label cardinality when using queries.yaml.

postgres_exporter.go, postgres_exporter_test.go
=> fixed version parsing for Windows and EnterpriseDB

cmd/postgres_exporter/postgres_exporter.go
This did in fact turn out to be an oversight in the error handling. Now, any
error in the initial connection path will always trip pg_up to be 0.
Fixes #160
=> Ensure pg_up is always set to 0 when the initial database connection fails

cmd/postgres_exporter/pg_setting.go, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_test.go, cmd/postgres_exporter/tests/test-smoke, magefile.go
Introduced by #162.
This patch includes the fix, a test in the integration smoke-tests, as well as linter and fmt'ing fixes from the conversion to the new build system.
=> Fix pg_up never being set to 1

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_test.go, cmd/postgres_exporter/tests/username_file, cmd/postgres_exporter/tests/userpass_file
Fixes #188.
It occurs to me that you might have a concern about this changing behaviour in the case where existing users have worked around the problem by URL encoding the password themselves before supplying it (it will double encode resulting in authentication failure). If that's the case, I can change the PR so that it only applies the encoding if it detects that it is necessary; this should leave existing unaffected users unaffected, but also fix the problem for those that are.
=> URL encode username/password fields

README.md, cmd/postgres_exporter/pg_setting.go, cmd/postgres_exporter/pg_setting_test.go, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_integration_test.go, cmd/postgres_exporter/postgres_exporter_test.go
Hi Everyone!
I've added an ability to define different data sources for one exporter setup.
Changes:
1. "server" label is added to each exported metric. "server" label is parsed from DSN and represents "host:port" pair.
2. To configure different data source you should list them in `DATA_SOURCE_NAME` separated by the comma.
3. I've added `disable-settings-metrics` flag to the command line in order to avoid panics in Prometheus client when different Postgres versions return different descriptions for settings.
=> multi server exporter is introduced

README.md, cmd/postgres_exporter/tests/test-smoke
Remove support for version on that are [no longer supported](https://www.postgresql.org/support/versioning/) by the postgre team
It is worth mentioning that the docker image for postgres 9.1 fails to build due an issue w/ apt-get and debian indexes.
see https://travis-ci.org/asherf/postgres_exporter/builds/546034279
=> remove unsupported postgres versions

cmd/postgres_exporter/postgres_exporter.go
Quick fix, to disable collection of static_version if default metrics are disabled.
It throws an error, when connected to multiple databases on same server:
```
An error has occurred while serving metrics:
collected metric "pg_static" { label:<name:"server" value:"172.16.110.20:5432" > label:<name:"short_version" value:"11.2.0" > label:<name:"version" value:"PostgreSQL 11.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit" > untyped:<value:1 > } was collected before with the same name and label values
```
=> No version when default metrics disabled

queries.yaml
Prometheus supports double/float numbers just fine so no need to truncate the number. Without this you get millisecond (or less?) resolution for your replication lag
=> No need to truncate replication lag to integers

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_test.go
This is useful if your database uses true/false for state and want to make prometheus alerts based on that.
Before, booleans were not able to be parsed.  See issue #201
=> Support for boolean data types as metrics

README.md, cmd/postgres_exporter/postgres_exporter.go
This feature adds an option to dynamically retrieve the available databases / DSN's from a single DSN. This allows users to only configure a single DSN per database server and scrape metrics for all databases on the configured servers.
=> Add option to automatically discover database names

magefile.go
magefile.go was using deprecated archiver methods (e.g. `archiver.Zip.Make(...)` ), I updated it to use the new version of the archiver library.
=> Updated the magefile.go to use new version of archiver library

README.md
Make the SQL work in automated deployments where it will be repeated many times.
I needed to make the provided SQL part work in Ansible without elaborate checks on the Ansible part, so I modified some parts.
It might be overkill for the README file, so I leave that decision to the maintainer.
Cheers!
=> README: SQL that supports re-execution

cmd/postgres_exporter/postgres_exporter.go
In a k8s cluster, client_addr cannot be used to identify clients. application_name would be really useful.
=> Use application_name column as a label

README.md, cmd/postgres_exporter/postgres_exporter.go, tools/src
This adds an option to exclude arbitrary databases when enabling `--auto-discover-databases`
=> exclude databases

README.md, cmd/postgres_exporter/postgres_exporter.go
Currently when using the option `auto-discover-databases`, templates and databases that does not allow connections are returned in the result leading to errors when the exporter try to connect to them.
This PR aims to get ride of them by adding a filter in the request used by the option.
The fields `datallowconn` and `datistemplate` are presented in the PG version supporter by the exporter so it do not include breaking changes
=> Template and allowconn discovery

queries.yaml
Returning a (long gone) timestamp does the right thing for alerting
PromQL queries ("alert if older than"), while `NaN` is rather intractable.
=> Provide more helpful default values for tables that have never been vacuumed

cmd/postgres_exporter/postgres_exporter.go
pg_current_wal_lsn is currently DISCARDed here: https://github.com/wrouesnel/postgres_exporter/blob/master/cmd/postgres_exporter/postgres_exporter.go#L244
I believe this is because it's currently a string value that is the position within the WAL logs, and isn't immediately useful in graphing.
This PR adds a metric `pg_current_wal_lsn_bytes`, which is the diff between the current position and the initial WAL position of `0/0` -- effectively a translation of the WAL log position into bytes, such that `rate(pg_stat_replication_pg_currentl_wal_lsn_bytes)` can be meaningful on graphs.
We use this metric to see the rate of WAL entries being created on the primary, independently of whether the primary and secondary are becoming further behind or catching up - you can then tell the difference …
=> Expose pg_current_wal_lsn_bytes

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_test.go
Sometimes PostgreSQL passwords contain special characters, such as `=`, since it's also allowed to be there, and it rises a problem in finger generation code, which will mistakenly report this scenario as `invalid dsn`.
This PR fixes the problem with `=` character inside the password by splitting `=` only once, so:
- The string before `=` will be treated as key.
- The string after `=` will be treated as a value.
=> Don't stop generating fingerprint while encountering value with "=" sign

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_integration_test.go, cmd/postgres_exporter/postgres_exporter_test.go, queries.yaml
In the user queries.yml file, the created namespaces can now be optionally
cached by setting cache_seconds, which will prevent the query being re-run
within that timeframe if previous results are available.
Supercedes #211 which became unmergeable due to conflicts.
=> Add support for optional namespace caching.

README.md, cmd/postgres_exporter/postgres_exporter.go
Closes #326 as is provides a viable solution to use a K8S init container
to fully contruct the PostgreSQL URI and 'hand it over' to the postgres_exporter
process.
=> Add support for 'DATA_SOURCE_URI_FILE' envvar.

README.md, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_integration_test.go, cmd/postgres_exporter/postgres_exporter_test.go, queries.yaml
- Fix problem: [329](https://github.com/wrouesnel/postgres_exporter/issues/329);
- Feature:  added new field "master" to queries.yaml. Now you can change behavior of query. If "master" is true, query will be call only on once database in instance;
- Change queries.yaml for work with autoDiscoveryDatabases options: added current database name to metrics becase any database in cluster maybe have same table names; added "master" field for query instance metrics.
=> fix master database behavior

cmd/postgres_exporter/postgres_exporter.go
These are useful for knowing if WAL archiving is working successfully.
I believe the pg_stat_archiver view was added in 9.4 (which is the oldest currently-supported version of postgres), but it's not clear whether I can stop this being queried in older versions.
=> Export pg_stat_archiver metrics

cmd/postgres_exporter/postgres_exporter.go
Failures in parsing the user's queries are just being swallowed, which
makes troubleshooting YAML issues frustrating/impossible. I'm presuming
this was not intentional, since there is error handling code in the
function that calls this one, though it is unreachable as far as I can
tell without this change.
=> Don't ignore errors in parseUserQueries

queries.yaml
this fixes the matching of the returned metric value to the metric name
=> fix pg_database_size_bytes metric in queries.yaml

Dockerfile
=> Switch to debian baseimage for docker

README.md
this has a minor change to the wording and a couple of examples to demonstrate
the use of DATA_SOURCE_URI.
=> update docs with examples of DATA_SOURCE_URI

README-RDS.md, queries.yaml
excluding rolname 'rdsadmin' in pg_stat_statements, and adding notes on using postgres-exporter with AWS:RDS
=> Fix queries for awsrds

README.md
Needed this to fix errors like `* collected metric "pg_stat_statements_blk_write_time_seconds" { label:<name:"datname" value:"postgres" > label:<name:"rolname" value:"postgres_exporter" > label:<name:"server" value:"localhost:5432" > counter:<value:0 > } was collected before with the same name and label values`.
=> Add pg_stat_statements view for non-superuser instructions

magefile.go
GOOS="linux"
GOARCH="mips64le"
GOROOT="/opt/go/go1.14.6"
the issues: https://github.com/wrouesnel/postgres_exporter/issues/417
lol,I solved
I forgot to put some material on it.
[root@localhost postgres_exporter]# arch
mips64el
[root@localhost postgres_exporter]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@localhost 桌面]# uname -a
Linux localhost.localdomain 3.10.0-693.21.1.ns7.007.mips64el #1 SMP PREEMPT Wed May 23 19:09:06 CST 2018 mips64el mips64el mips64el GNU/Linux
[root@localhost postgres_exporter]# export DATA_SOURCE_NAME="postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
[root@localhost postgres_exporter]# ./postgres_exporter
INFO[0000] Established new database connection to "localhost:5432". …
=> Loongson CPU mips64le compiled through.

cmd/postgres_exporter/postgres_exporter.go
The existing 'pg_stat_replication' data does not
include stats for inactive replication slots. This
commit adds a minimal amount of metrics from
'pg_replication_slots' to know if a slot is
active and its lag.
This is helpful to detect if an inactive slot
is causing the server to run out of storage due
to an inactive slot blocking WAL flushing.
=> Add query for 'pg_replication_slots'

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_test.go
This fails a bit nicer when the data sources env variables are not correctly configured.
=> Do not panic on incorrect env

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_integration_test.go, cmd/postgres_exporter/postgres_exporter_test.go, cmd/postgres_exporter/tests/user_queries_test.yaml, queries.yaml
Prior to this change, the custom queries were restricted to counters and gauges.
This change introduces a new ColumnUsage, namely HISTOGRAM, that expects the column to contain an array of upper inclusive bounds for each observation bucket in the emitted metric.  It also expects three more columns to be present with the suffixes:
- `_bucket`, containing an array of cumulative counters for the
observation buckets;
- `_sum`, the total sum of all observed values; and
- `_count`, the count of events that have been observed.
A flag has been added to the MetricMap struct to easily identify metrics that should emit a histogram and the construction of a histogram metric is aided by the pg.Array function and a new helper dbToUint64 function.
Finally, and example of usage is given in queries.yaml. …
=> Introduce histogram support

README.md, cmd/postgres_exporter/postgres_exporter.go
=> Have a custom prefix for each of the default metrics created by postgres_exporter

cmd/postgres_exporter/postgres_exporter.go
Since we cannot know in advance the metrics which the exporter will generate, the workaround is to run a Collect and return the metric descriptors. This is problematic when the connection to the PostgreSQL instance cannot be established straight from the start. This patch makes Describe return no descriptors, effectively turning the collector in an unchecked one, which we're in the typical use case here: https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?tab=doc#hdr-Custom_Collectors_and_constant_Metrics.
Related to #415
=> Do not try to return metric descriptors in Describe

queries.yaml
In some cases master can show `pg_last_xact_replay_timestamp()` from past, which can cause the exporter to show ever-growing value for the lag. This fixes the issue.
I've got the idea for fix from:
* [mailing list](https://postgrespro.com/list/id/557EE9D7.50607@gmail.com)
* [DataDog bug fix](https://github.com/DataDog/integrations-core/pull/1172/files#diff-5557a2bc9bebe6d84b8a6fa72246b83bR214)
Example (from master):
```
[local]:5432 postgres@postgres=# SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as lag;
+----------------+
|      lag       |
+----------------+
| 3567749.711759 |
+----------------+
(1 row)
```
Same master, fixed query:
```
[local]:5432 postgres@postgres=# SELECT CASE WHEN NOT pg_is_in_recovery() THEN 0 ELSE GREATEST (0, EXTRACT(EPOCH FROM (now() - …
```
=> Improve PostgreSQL replication lag detection

cmd/postgres_exporter/postgres_exporter.go
When the connection to the PostgreSQL instance cannot be established straight at startup, a race condition can happen when autoDiscoverDatabases is true. If discoverDatabaseDSNs fails, no dsn is set as the master database, and, if scrapeDSN succeeds, checkMapVersions will have omitted the default metrics in the server metric map. The metric map won't be updated unless the version returned by the PostgreSQL instance changes. With this patch, scrapeDSN won't be run unless discoverDatabaseDSNs succeeded and thus the race condition is eliminated.
=> Recover when connection cannot be established straight at startup

cmd/postgres_exporter/postgres_exporter.go
Support connstring DSNs (`host=... user=... password=... dbname=...`) in
addition to URIs (`postgresql://user:pass@host/dbname`) for purposes of
database discovery.
Connstring syntax is needed to support accessing PostgreSQL via Unix
domain sockets (`host=/run/postgres`), which is not really possible with
URI syntax.
Fixes: #293
=> Support connstring syntax when discovering databases

cmd/postgres_exporter/postgres_exporter.go
User can define the range of database server version where query is to be executed in yml configuration file.
If user want to run the query on database version greater than 10.0.0, use below format.
runonserver: ">=10.0.0"
Below are the example of db version range user can defined in yml file.
<=10.1.0
>=12.1.0
=11.0.0
<9.6.0 || >=11.0.0
=> User defined configuration to run the query for different database server version from single yml file

.circleci/config.yml, README.md
Setup integration test matrix in CircleCI.
* Update README integration testing list.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Add integration tests

CHANGELOG.md
Attempt 2 to fixup CHANGELOG for promu release.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Remove v from changelog tags

README.md, cmd/postgres_exporter/pg_setting.go, cmd/postgres_exporter/postgres_exporter.go, go.mod, go.sum, scripts/errcheck_excludes.txt
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> Switch to go-kit log and enable TLS/Basic auth

cmd/postgres_exporter/postgres_exporter.go
Use Prometheus common/version to print --version output.
* Add `-h` short help flag.
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/492
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Fix version flag

README.md, cmd/postgres_exporter/postgres_exporter.go
Add `include-databases` param, which works as an antagonist of `exclude-database` when autodiscovery is on. The motivation is to add the ability to use the power of autodiscovery of database (read as auto create of DSNs), but query an only subset of found DBs.   It also saves the current behavior with the `master` flag for 'main'.
=> Add ability to set allow DBs list

README.md, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/postgres_exporter_integration_test.go
The introduction of the include databases flag disables the auto discovery flag completely, this PR will fix that.
=> fix parsing include databases

queries.yaml
Fixes regression introduced in https://github.com/prometheus-community/postgres_exporter/pull/435
=> fix examples queries: change idle process metric name in order not to override built-in pg_stat_activity.

README.md
Reference here: https://grafana.com/docs/agent/latest/configuration/integrations/postgres-exporter-config/
Also, matches the environment variables section.
=> Clarify default values for CLI flags

README.md
Starting from version 10, PostgreSQL includes a built-in role `pg_monitor` meant for use by monitoring tools. This PR adds documentation about granting the role when running postgres_exporter as non-superuser. Fixes #258.
=> #258 Document running as non-superuser on PostgreSQL versions 10 or newer.

queries.yaml
This metric can be very expensive to store in prometheus and has the potential to create an unreasonably large cardinality set of metrics so warn the user.
This was brought up in #549 
ping @SuperQ 
=> Add a warning for pg_stat_statements

cmd/postgres_exporter/pg_setting.go
Azure Flexible Server (currently in preview but slated to become generally available before the end of the year) apparently added a custom GUC with type int, but their default value is `Disabled`, breaking postgres_exporter:
```
=> SELECT name, setting, vartype, COALESCE(unit, ''), short_desc FROM pg_settings WHERE vartype IN ('bool', 'integer', 'real') AND name = 'sync_commit_cancel_wait';                                   
name           | setting  | vartype | coalesce |                                    short_desc                                     
-------------------------+----------+---------+----------+-----------------------------------------------------------------------------------
sync_commit_cancel_wait | Disabled | integer |          | Allow cancellation of waiting for …
```
=> Avoid parsing error from bogus Azure Flexible Server custom GUC

README.md
Getting the error when adding non-root postgres user for exporter:
```
postgres=# CREATE OR REPLACE FUNCTION get_pg_stat_statements() RETURNS SETOF pg_stat_statements AS
postgres-# $$ SELECT * FROM public.pg_stat_statements; $$
postgres-# LANGUAGE sql
postgres-# VOLATILE
postgres-# SECURITY DEFINER;
ERROR:  type "pg_stat_statements" does not exist
```
Add following sql command for enable pg_stat_statements:
```
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
```
=> Add error prone SQL in README.md

CHANGELOG.md, cmd/postgres_exporter/main.go, cmd/postgres_exporter/server.go, collector/collector.go, collector/pg_database.go, collector/server.go, queries.yaml
Converts the pg_database metrics from queries.yaml to a built in collector. This is enabled by default because it is not likely to be a performance problem and likely very useful data.
=> Add pg_database collector

postgres_exporter.rc
This was not updated when the arguments were last updated. No need to list the options here IMO.  
I'm not positive if this file is actually used anywhere.
=> Update rc file to reflect newer args

CHANGELOG.md, README.md, cmd/postgres_exporter/main.go, cmd/postgres_exporter/postgres_exporter.go, collector/collector.go, collector/pg_stat_bgwriter.go, collector/server.go, postgres_mixin/dashboards/postgres-overview.json
This moves the metrics that are queried from pg_stat_bgwriter into a dedicated collector instead of dynamically generating queries and metrics from a map. It adopts a new, consistent namespace `postgres` for its metrics and includes the `_total` suffix on all of the counters to match prometheus standards. 
This implementation uses QueryRowContext to allow for later addition of context for cancellation. The Postgres docs state that this should only ever be a single row.
This ignores any sort of future Collector interface to keep the surface area small and to allow for that interface to get fleshed out before implementation.
The previous implementation had a label `server`, so I kept it but I am unsure if it's even useful. 
@SuperQ This should not be merged before the v0.10.0 tag. I am also …
=> refactor pg_stat_bgwriter metrics into standalone collector

go.mod, go.sum
Hello,
The [CVE-2022-21698](https://github.com/advisories/GHSA-cg3q-j54f-5p7p) has been published on 2022-02-15, and affect this exporter.
We need to update client_golang to 1.11.1 to patch it.
=> fix: CVE-2022-21698

postgres_mixin/alerts/postgres.libsonnet
Previous query results in an error reported by prometheus:
> Error executing query: invalid parameter "query": 2:18: parse error: unexpected <by> in aggregation
This PR is an attempt to fix this.
=> postgres_mixin/alerts: fix incorrect promql aggregation

README.md
It looks like postgres 14.1 was added to CI here:
https://github.com/prometheus-community/postgres_exporter/commit/fcb2535affa0f97c7a11439c19de6a7ff793e0df
See also: https://github.com/prometheus-community/postgres_exporter/issues/651#issuecomment-1156947591
=> Update readme to include Postgres 14 support

collector/pg_stat_bgwriter.go
"Scan error on column index 2, name \"checkpoint_write_time\": converting driver.Value type float64 (\"6.594096e+06\") to a int: invalid syntax #633"
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/633
Signed-off-by: bravosierrasierra <bravosierrasierra@users.noreply.github.com>
=> Fix checkpoint_write_time value type

collector/pg_stat_bgwriter.go
Error:
```sh
sql: Scan error on column index 3, name \"checkpoint_sync_time\": converting driver.Value type float64 (\"1.876469e+06\") to a int: invalid syntax
```
See also:
https://github.com/prometheus-community/postgres_exporter/issues/633
https://github.com/prometheus-community/postgres_exporter/pull/666
Thank you!
=> Fix checkpoint_sync_time value type

cmd/postgres_exporter/pg_setting.go
Fixes https://github.com/prometheus-community/postgres_exporter/issues/539
=> 4kB size added for postgres with 4kB block_size

cmd/postgres_exporter/probe.go
Hello. I saw that `/probe` path doesn't execute queries from file, doesn't collect different metrics, which are exist over default `/metrics` path and so on. I think, that it is unclear and unexpected behaviour. Could you please review this and tell me what I can do yet to merge it?
=> Extending /probe path metrics

postgres_mixin/dashboards/postgres-overview.json
Some changes to accommodate the [dashboard linter](https://github.com/grafana/dashboard-linter), caught several minor (or moderate?) issues.
- Most (all?) queries were not using the `$job` matcher
- The template vars were set with default selected values, which weren't ideal
- The instance template var was not filtering to instances belonging to the selected job(s)
- Reorganized template vars from broadest to most specific
=> Dashboard linting improvements for mixin

cmd/postgres_exporter/pg_setting.go
For Postgres 15  database, exporter panic with error:
`panic: Unknown unit for runtime variable: "64kB"
goroutine 25 [running]:
main.(*pgSetting).metric(0xc0005790e0, 0xc0003b9c50?)
/app/cmd/postgres_exporter/pg_setting.go:87 +0x2fc
main.querySettings(0x0?, 0xc0001b4fd0)
/app/cmd/postgres_exporter/pg_setting.go:56 +0x29e
main.(*Server).Scrape(0xc0001b4fd0, 0xc000026011?, 0xd0?)
/app/cmd/postgres_exporter/server.go:121 +0xd7
main.(*Exporter).scrapeDSN(0xc0001bc0c0, 0xc0000ce764?, {0xc000026011, 0x55})
/app/cmd/postgres_exporter/datasource.go:116 +0x1cd
main.(*Exporter).scrape(0xc0001bc0c0, 0xc0000ce660?)
/app/cmd/postgres_exporter/postgres_exporter.go:711 +0x235
main.(*Exporter).Collect(0xc0001bc0c0, 0xc0000ce760?)
/app/cmd/postgres_exporter/postgres_exporter.go:600 +0x27 …
=> New unit value 64kB

collector/pg_replication_slots.go, collector/replication_slots.go
given the push to codify some of the queries.yaml statements, we want to add logical replication metrics. This metric will be labeled on the slot name and the metric will be the distance between the `current_wal_lsn()` and the confirmed_flush_lsn
=> adding codified functionality for logical replication metrics

cmd/postgres_exporter/probe.go, collector/probe.go
Currently each probe creates a new DB connection which is never closed.  This fix closes the connection upon the completion of a probe.  An alternative solution would be to inject a DB object into the handleProbe handler, but that would be a larger scope change.
Tested locally and scrapes correctly without increasing the number of connections in Postgres.  
edit: since opening the PR I have been running this in a dev environment and scrapes are working as expected and connection level is staying stable.
Will fix https://github.com/prometheus-community/postgres_exporter/issues/727
Signed-off-by: Kurtis Bass <kurtis.bass@hinge.co>
=> Close DB connection after probe completes.

cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/queries.go
It is necessary to be able to exclude backups from long-running
transaction alerts, as they are to be expected. With the current
pg_stat_activity metric there is no ability to filter out
specific users or application names.
Resolves #668
=> Capture usename and application_name for pg_stat_activity

cmd/postgres_exporter/main.go, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/probe.go, collector/collector.go, collector/pg_database.go, collector/pg_stat_bgwriter.go, collector/probe.go, collector/replication_slots.go
The pg_database collector was not respecting the --exclude-databases flag and causing problems where databases were not accessible. This now respects the list of databases to exclude.
- Adjusts the Collector create func to take a config struct instead of a logger. This allows more changes like this in the future. I figured we would need to do this at some point but I wasn't sure if we could hold off.
- Split the database size collection to a separate query when database is not excluded.
- Comment some probe code that was not useful/accurate
=> Fix exclude-databases for collector package

collector/replication_slots.go
Change the data type of `active` from int64 to bool. The documentation confirms that this is a boolean field. https://www.postgresql.org/docs/current/view-pg-replication-slots.html
fixes #769
=> Fix column type for pg_replication_slots

README.md
These have not been kept up to date.
=> Update README cli flags

queries.yaml
Make the example queries.yaml `pg_stat_statements` query safer.
* Select the top 10% of queries by total query time.
* Only expose the top 100 queries by total query time.
* Keep only the most useful metrics.
* Comment out the example by default.
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/549
=> Reduce cardinality of pg_stat_statements

cmd/postgres_exporter/pg_setting.go, cmd/postgres_exporter/pg_setting_test.go
pg_settings metrics have different short descriptions in different pg versions #770
Similar to #598
=> Fix pg_setting different help values

cmd/postgres_exporter/datasource.go, config/dsn.go, config/dsn_test.go
Adds support for the alternate postgres:// prefix in URLs. It's maybe not the cleanest approach, but works.  Hoping I can either get some pointers on a more appropriate patch, or that we could use this in the interim to unblock this use-case.
Fixes: #660
=> Supports alternate postgres:// prefix in URLs

collector/pg_database.go, collector/pg_stat_bgwriter.go, collector/replication_slots.go
Use individual collector metric descriptor vars to help avoid miss-mapped or unused metrics.
=> Refactor collector descriptors

cmd/postgres_exporter/postgres_exporter.go, collector/pg_stat_database.go
=> Convert pg_stat_database to new collector model

collector/pg_stat_database.go
The signature for creating a collector changed and CI didn't retrigger. Move metrics out of map and into individual vars.
=> Fix pg_stat_database collector

README.md, cmd/postgres_exporter/main.go
Now that we have deprecated extended queries we can deprecate related database features.
* Deprecate flags/functions around auto discover databases.
* Deprecate flags/functions for additional constant labels.
=> Deprecate additional database features

collector/collector.go, collector/instance.go, collector/pg_database.go, collector/pg_database_test.go, collector/pg_postmaster.go, collector/pg_postmaster_test.go, collector/pg_process_idle.go, collector/pg_replication_slot.go, collector/pg_replication_slot_test.go, collector/pg_stat_bgwriter.go, collector/pg_stat_bgwriter_test.go, collector/pg_stat_database.go, collector/pg_stat_statements.go, collector/pg_stat_statements_test.go, collector/pg_stat_user_tables.go, collector/pg_stat_user_tables_test.go, collector/pg_statio_user_tables.go, collector/pg_statio_user_tables_test.go, collector/probe.go
The intent is to use the instance struct to hold the connection to the database as well as metadata about the instance. Currently this metadata only includes the version of postgres for the instance which can be used in the collectors to decide what query to run. In the future this could hold more metadata but for now it keeps the Collector interface arguments to a reasonable number.
=> Add the instance struct to handle connections

collector/pg_database.go, collector/pg_database_test.go, collector/pg_postmaster.go, collector/pg_postmaster_test.go, collector/pg_process_idle.go, collector/pg_replication_slot.go, collector/pg_replication_slot_test.go, collector/pg_stat_bgwriter.go, collector/pg_stat_bgwriter_test.go, collector/pg_stat_database.go, collector/pg_stat_database_test.go, collector/pg_stat_statements.go, collector/pg_stat_statements_test.go, collector/pg_stat_user_tables.go, collector/pg_stat_user_tables_test.go, collector/pg_statio_user_tables.go, collector/pg_statio_user_tables_test.go
Resolves: https://github.com/prometheus-community/postgres_exporter/issues/818
Make all row scans that gather values nullable except the ones that gather absolute values. Nulls are emitted to prometheus as "0" values or "unknown" for labels. Also wrote an additional set of tests to make sure nulls are caught and dealt with properly.
=> Bug fix: Make collector not fail on null values

collector/pg_replication_slot.go
Fixed case when replica has replication slot and we cannot perform some wal control function during pg recovering (replication itself). 
Wrong query:
```
SELECT
slot_name,
pg_current_wal_lsn() - '0/0' AS current_wal_lsn,
coalesce(confirmed_flush_lsn, '0/0') - '0/0',
active
FROM
pg_replication_slots;
```
Fixed query:
```
SELECT
slot_name,
CASE
WHEN PG_IS_IN_RECOVERY() THEN pg_last_wal_receive_lsn() - '0/0'
ELSE pg_current_wal_lsn() - '0/0' END AS current_wal_lsn,
COALESCE(confirmed_flush_lsn, '0/0') - '0/0',
active
FROM pg_replication_slots;
```
=> Fixed replication pgReplicationSlotQuery execution for replica

README.md, cmd/postgres_exporter/postgres_exporter.go, cmd/postgres_exporter/queries.go, collector/pg_locks.go, collector/pg_locks_test.go
Migrate the `pg_locks_count` query from `main` to the `collector` package.
=> Migrate pg_locks to collector package

collector/pg_process_idle.go, collector/pg_replication.go, collector/pg_replication_test.go
Fix up `replication` and `process_idle` Update input params to match the rest of the collectors.
=> Cleanup collectors

collector/pg_process_idle.go
The previous code just errored calling `Scan` on the row as the arrays are returned as strings that need to be decoded with `pq.Array`.
=> Unpack postgres arrays for process idle times correctly

.golangci.yml, collector/pg_database.go, collector/pg_replication_slot.go, collector/pg_statio_user_tables.go
* Disable unused-parameter check due to false positives on Collect() calls.
* Enable misspell.
* Simplify error returns.
=> Improve linting

collector/pg_process_idle.go
This is the extension to `pg_process_idle` metric that we've been using which I mentioned in #846 the other day.
It extends things to include `idle in transaction` and `idle in transaction (aborted)` in the monitored states and adds the state as a label.
=> Include all idle processes in the process idle metrics

collector/pg_stat_database.go, collector/pg_stat_database_test.go
Trying to debug https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/pull/581
(also clean up some metric validity checks)
=> Add a logger to stat_database collector

collector/pg_stat_statements.go, collector/pg_stat_statements_test.go
Update pg_stat_statements collector to handle the new column names in PostgreSQL 13.
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/502
=> Handle new pg_stat_statements column names

collector/pg_stat_statements.go
Fix all renames of `total_time` to `total_exec_time`.
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/502
=> Fixup new pg_stats_statements query

README.md
Add an example Prometheus scrape config, similar to the blackbox_exporter's example config.
Fixes: https://github.com/prometheus-community/postgres_exporter/issues/888
=> Add a multi-target example config

collector/collector.go, collector/instance.go, collector/probe.go
This no longer returns an error when creating a collector.instance when the database cannot be reached for the version query. This will resolve the entire postgresCollector not being registered for metrics collection when a database is not available. If the version query fails, the scrape will fail.
Resolves #880
=> Delay database connection until scrape

collector/pg_stat_database.go, collector/pg_stat_database_test.go
Null is a legit value for statsReset and we should treat it as such. That being said, not clear what the value should be if the timestamp is null
=> Bugfix: Make statsreset nullable

README.md
The cross-compilation command currently lists amd64 twice. This fixes it by changing the second to arm64.
=> Fix cross-compilation command in README.md

collector/pg_replication.go
Since postgres_exporter is being tested for versions above 10, I suggest replacing 
```
WHEN NOT pg_is_in_recovery() THEN 0
ELSE GREATEST (0, EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())))
```
to
```
WHEN NOT pg_is_in_recovery() THEN 0
WHEN pg_last_wal_receive_lsn () = pg_last_wal_replay_lsn () THEN 0
ELSE GREATEST (0, EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())))
```
Changed the way `pg_last_xact_replay_timestamp` works after 9.3
https://github.com/prometheus-community/postgres_exporter/issues/385
=> fix pg_replication_lag_seconds

collector/pg_stat_user_tables.go, collector/pg_stat_user_tables_test.go
This adds a new `pg_stat_user_tables_total_size` metric to the stat_user_tables collector. It uses the [`pg_total_relation_size()`](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-DBSIZE) function. (I had been using this via a modification to the query YAML file previously)
Note that #847 does something similar, but as a separate collector. This query is only scoped to user tables, not all relations.
=> stat_user_tables: Add total size metric

collector/pg_stat_activity_autovacuum.go, collector/pg_stat_walreceiver.go, collector/pg_xlog_location.go
These collectors are disabled by default, so unless enabled, they are not tested regularly.
=> Fix bugs mentioned in #908

cmd/postgres_exporter/pg_setting.go
These units can show up if you compile postgres  with a wal-blocksize of 1 or 2.
```
./configure --with-blocksize=8 --with-segsize=1 --with-wal-blocksize=2
```
Here's an admittedly cruddy Dockerfile to reproduce:
```
from debian:stable
RUN useradd -ms /bin/bash postgres
WORKDIR /home/postgres
RUN echo "deb http://deb.debian.org/debian/ bookworm main contrib non-free" > /etc/apt/sources.list
RUN apt-get update && apt-get upgrade
RUN apt-get install -y curl gcc libreadline8 libreadline-dev openssl zlib1g zlib1g-dev make
RUN curl https://ftp.postgresql.org/pub/source/v15.3/postgresql-15.3.tar.gz > postgresql-15.3.tar.gz
RUN tar xf postgresql-15.3.tar.gz
WORKDIR /home/postgres/postgresql-15.3
RUN ./configure --with-blocksize=8 --with-segsize=1 --with-wal-blocksize=1
RUN make
RUN make install …
```
=> Adds 1kB and 2kB units

cmd/postgres_exporter/probe.go
This would help debug a scenario like #917
=> Add error log when probe collector creation fails

collector/pg_replication_slot.go, collector/pg_replication_slot_test.go
Fixes https://github.com/prometheus-community/postgres_exporter/issues/959
=> pg_replication_slot: add slot type label

collector/pg_stat_database.go, collector/pg_stat_database_test.go
Hello,
for our use case is key to measure active time per database and this metric was missing in current version of `pg_exporter`.
In older version we add this metric manually via `queries.yaml` but this method is now not recommended.
=> pg_stat_database: added support for `active_time` counter

cmd/postgres_exporter/main.go
This is the only log message which didn't specify a level in the postgres_exporter. I am unsure if this log message should be info or debug, but leaning towards the more important since previously it would just always log.
The way I validated this was the only non-leveled logger was via grep. Both of these only returned this callsite previously:
``` shell
git grep 'logger\.Log'
git grep '\.Log(' | grep -v level
```
=> use Info level for excluded databases log message

collector/pg_database.go, collector/pg_database_test.go, collector/pg_roles.go, collector/pg_roles_test.go
Fixes https://github.com/prometheus-community/postgres_exporter/issues/996
This PR adds the possibility to gather metrics for Database and roles connection limits.
=> Add connection limits metrics for pg_roles and pg_database

collector/pg_replication_slot.go, collector/pg_replication_slot_test.go
=> feat: Add safe_wal_size and wal_status to replication_slot 

collector/pg_stat_database.go, collector/pg_stat_database_test.go
Fixes https://github.com/prometheus-community/postgres_exporter/issues/1044
Its quite hacky IMO, but please let me know what you think or how we could solve this otherwise.
=> fix: Only query active_time on pg>=14

README.md
Better example for the quick start with prometheus config and avoiding deprecated env variables.
=> Update README.md with better quick start example

collector/pg_stat_walreceiver.go
In a streaming replication setup that was created without replication manager (`repmgr`), the `stat_wal_receiver` collector does not return any metrics, because one value it wants to export is not present.
This is rather overly opinionated. The missing metric is comparatively uninteresting and does not justify discarding all the others. And replication setups created without `repmgr` are not exactly rare.
This commit makes the one relevant metric optional and simply skips it if the respective value cannot be determined.
=> Make walreceiver collector useful w/o repmgr

cmd/postgres_exporter/pg_setting.go
This fix is to cater to the Issue - https://github.com/prometheus-community/postgres_exporter/issues/1102, where the exporter is crashing with the following signature.
```
panic: "pg_settings_mem_guard_enable-auth-hook" is not a valid metric name
goroutine 52 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/value.go:129
main.(*pgSetting).metric(0xc00020c640, 0xc00020a2a0)
/app/cmd/postgres_exporter/pg_setting.go:99 +0x2ff
main.querySettings(0xc00022e070, 0xc00025a000)
/app/cmd/postgres_exporter/pg_setting.go:55 +0x1d8
main.(*Server).Scrape(0xc00025a000, 0xc00022e070, 0x0?)
/app/cmd/postgres_exporter/server.go:120 +0xc8
main.(*Exporter).scrapeDSN(0xc000174000, 0xc00022e070, {0xc0000be140, …
```
=> Fix to replace dashes with underscore in the metric names

.circleci/config.yml, collector/pg_stat_bgwriter.go, collector/pg_stat_bgwriter_test.go, collector/pg_stat_checkpointer.go, collector/pg_stat_checkpointer_test.go
Fix https://github.com/prometheus-community/postgres_exporter/issues/1060
See: 
* https://www.dbi-services.com/blog/postgresql-17-new-catalog-view-pg_stat_checkpointer/
* https://www.postgresql.org/docs/16/monitoring-stats.html#MONITORING-PG-STAT-BGWRITER-VIEW
* https://www.postgresql.org/docs/17/monitoring-stats.html#MONITORING-PG-STAT-BGWRITER-VIEW
Thank you!
=> Checkpoint related columns in PG 17 have been moved from pg_stat_bgwriter to pg_stat_checkpointer

collector/pg_stat_statements.go, collector/pg_stat_statements_test.go
pg_stat_statements column names changes for Postgresql >= 17.0.0.
Migration notes can be found here:
https://www.postgresql.org/docs/current/release-17.html#RELEASE-17-MIGRATION
=> pg_stat_statements PG17

collector/pg_replication_slot.go, collector/pg_replication_slot_test.go
This PR fixes #1097 to handle pg < 13 for `pg_replication_slots`.
The original feat was #1027
=> fix: handle pg_replication_slots on pg<13

collector/pg_replication.go, collector/pg_replication_test.go
The exported replication lag does not handle all failure modes, and can report 0 for replicas that are out of sync and incapable of recovery.
A proper replacement for that metric would require a different approach (see e.g. #1007), but for a lot of folks, simply exporting the age of the last replay can provide a pretty strong signal for something being amiss.
I think this solution might be preferable to #977, though the lag metric needs to be fixed or abandoned eventually.
=> Export last replay age in replication collector

collector/pg_stat_checkpointer.go, collector/pg_stat_checkpointer_test.go
Hello,
Here a fix for https://github.com/prometheus-community/postgres_exporter/pull/1072#issuecomment-2503906073 where the collector fails on pg<17 when we use the exporter with the multi-target pattern
Thank you!
=> Skip pg_stat_checkpointer collector if pg<17

README.md, collector/pg_stat_progress_vacuum.go, collector/pg_stat_progress_vacuum_test.go
This pull request adds a new collector that exposes metrics from `pg_stat_progress_vacuum`, enabling visibility into in-progress VACUUM operations. The collected metrics include:
- Current phase of the vacuum (folllowing the State Set pattern)
- Heap blocks scanned / vacuumed
- Index vacuum cycle count
- Dead tuple counts and limits
This collector queries the underlying function `pg_stat_get_progress_info('VACUUM'::text)` directly rather than using the `pg_stat_progress_vacuum` view.
- Added unit tests, following the same structure as existing collectors (e.g. pg_stat_user_tables_test.go)
- Manually tested against live PostgreSQL instances with vacuum activity, using controlled workloads to generate observable vacuum progress
- Verified that metrics appear and update correctly on the …
=> Adds pg_stat_progress_vacuum collector

collector/pg_stat_user_tables.go, collector/pg_stat_user_tables_test.go
pg_total_relation_size gets the size of the relation + indexes and toast, however we need to know just the size of the table itself. You can get this info from pg_table_size. Should be safe to add, this function was added back in 2010.
=> Record table only size bytes as well in addition to the total size bytes

README.md, collector/collector.go, collector/pg_stat_statements.go, collector/pg_stat_statements_test.go
The feature must be enabled via flag or via environment variable.
The query is not added to every metrics, but instead of new metric stat_statement_query_id is introduced that contains mapping between queryId and query.
Fix #813
=> Export query itself together with queryId in stat_statement metrics

cmd/postgres_exporter/server.go
Previously if any errors were encountered by queryNamespaceMappings, only a count of those errors was returned - making debugging those errors harder than it needs to be.
I'm changing this to immediately return nil if no errors are encountered, and otherwise an error will be formatted with each of the namespaces and what the error was for that namespace.
Additionally, if any errors were encountered during querySettings, they were potentially obscured by queryNamespaceMappings errors. I've added an immediate return if errors are found during querySettings to ensure these errors are visible.
=> Feat: Improve Error Handling for Server.Scrape

collector/pg_process_idle.go
This semicolon breaks the query
/cc @kmoppel
=> Fix #1185 bug
