- README.md
change port number in README.md file
> README.md: Update to new default port 9187

- postgres_exporter.go
Sorry for the unrelated changes, apparently the code wasn't properly gofmt'd before.
Fixes #38
> Use correct SemVer range condition

- Makefile
- postgres_exporter.go
- postgres_exporter_test.go
Related issue is #38. Time to start expanding functional test coverage since the integration tests missed this.
> Add a test case to detect regression on issue fixed by PR #39.

- postgres_exporter.go
https://github.com/wrouesnel/postgres_exporter/issues/47
> Using a connection pool of size 1 instead of reestablishing connection all the time

- .gitignore
- .travis.yml
- Makefile
- README.md
- concatenate_coverage
- postgres_exporter.go
- postgres_exporter_integration_test.go
- postgres_exporter_integration_test_script
- postgres_exporter_test.go
- tests/test-smoke
Add coverage tests and badges, link up with go report card.
> Improved code quality

- postgres_exporter.go
see https://github.com/wrouesnel/postgres_exporter/issues/136
> fix invisibility of "/metrics"

- Makefile
- postgres_exporter.go
Closes a bundle of minor issues.
> v0.4.2 changes.

- cmd/postgres_exporter/pg_setting.go
- cmd/postgres_exporter/pg_setting_test.go
Fixes #173 
(or will do once we establish a test which reproduces it)
> Fix issue #173

- cmd/postgres_exporter/tests/docker-postgres-replication/Dockerfile.p2
- cmd/postgres_exporter/tests/docker-postgres-replication/docker-entrypoint.sh
We had a problem with the replication test due to some unknown change upstream. This PR should fix it.
EDIT: For posterity, it looks like 1 docker image in the chain didn't have ping for some reason?
> Fix the replication test.

- cmd/postgres_exporter/postgres_exporter.go
Just something small I found when reading through the code.
Thanks for this project ❤️
> Fix comments about DATA_SOURCE_* environment variable usage

- cmd/postgres_exporter/postgres_exporter.go
Added a query that returns results without state.
> add query for v9.1

- README.md
This functionality was added in c225a1e1949e40d387b630683427cb0db259753f
but not documented.
> Document --constantLabels

- cmd/postgres_exporter/postgres_exporter.go
- cmd/postgres_exporter/postgres_exporter_test.go
fix of https://github.com/wrouesnel/postgres_exporter/issues/243
> fix-param-env-key fix spelling of env parameter

- README.md
This solves the problem that certain metrics didn't produce a value.
> Update the running as non-superuser section.

- cmd/postgres_exporter/postgres_exporter.go
- cmd/postgres_exporter/postgres_exporter_test.go
See https://github.com/wrouesnel/postgres_exporter/issues/245
> fix panic on shutdown server

- README.md
See https://github.com/asherf/postgres_exporter/tree/badges#postgresql-server-exporter
12m pulls!!  👍 👏
> Add badge for docker pulls.

- cmd/postgres_exporter/postgres_exporter.go
- cmd/postgres_exporter/postgres_exporter_integration_test.go
- cmd/postgres_exporter/postgres_exporter_test.go
Minor style fix that will reduce the number of merge conflicts in the future PRs.
> Group and sort imports.

- Dockerfile
Docker file added multistage build to add non-root user running under user ID:20001 for image.
Reduces attack surface by not running image as root user
> Added non-root user to dockerfile 

- cmd/postgres_exporter/postgres_exporter.go
Some backstory
==============
I was attempting to use postgres_exporter with the official Docker
container (https://hub.docker.com/_/postgres) In a Kubernetes
StatefulSet, with a side-car configuration, but found that I wasn't able
to connect even with sharing the Postgres Unix listening socket, between
both containers. After copying the container over to an Alpine base I
quickly found out that the postgres_exporter was actually starting
before the main Postres container had dropped the unix socket onto the
file system, a quick work around is to write a bash for loop checking
for the existence of a unix socket, however this would require
maintaining a container, besides other users may find retries useful on
startup.
Implementation
==============
All changes are made to the getServer …
> Add retries to getServer()

- README.md
To resolve the error below, it was necessary to add a new grant to the database postgres.
Error: 'pq: permission denied for database \ "postgres \"'
> Add SQL for grant connect

- queries.yaml
Supercedes #35 by fixing the original issues mentioned in comments.
> Feature add pg stat statements

- example.alerts.yml
Adds a file containing some basic alerting rules for Prometheus as a launch point for more community contributions (or just when I get around to coming up with some more I'm interested in).
Resolves #68.
> Add example.alerts.yml

- magefile.go
> ARM64 platform

- cmd/postgres_exporter/postgres_exporter.go
> Fixed "Scrape Duration" if psql down

- cmd/postgres_exporter/postgres_exporter.go
The right way to fix #495 
Lets not forget about older postgres version.
> Fix replication_slot query all supported versions

- MAINTAINERS.md
> Add @sysadmind as a maintainer

- .github/ISSUE_TEMPLATE/bug_report.md
- cmd/postgres_exporter/postgres_exporter.go
Fix a few instances of PostgresSQL -> PostgreSQL.
> Fix misspelling of PostgreSQL

- collector/pg_stat_bgwriter.go
Create a branch for bug fixes to 0.11.0.
> Pick fixes into release-0.11

- cmd/postgres_exporter/probe.go
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> Set gauge to 1 when collector is successful

- postgres_exporter.rc
Fix for issue #754 
Adding to parameters for **daemon**
* -f: redirect output
* -T: add syslog_tag
Signed-off-by: Mike <gavrikster@gmail.com>
> send stdout/stderr to syslog

- README.md
Update the supported versions based on what we actually test in CI.
> Update versions listed in the README

- CHANGELOG.md
@SuperQ I already have a branch release-0.13 ready to go. After this is merged, I will cherry-pick this commit and tag another release.
> Update changelog for release 0.13.2

- collector/collector_test.go
- collector/pg_xlog_location.go
- collector/pg_xlog_location_test.go
> Gitlab collector: Xlog location collector and test

- collector/pg_statio_user_indexes.go
- collector/pg_statio_user_indexes_test.go
> Gitlab Collector: User Index io stats collector and test

- collector/pg_long_running_transactions.go
- collector/pg_long_running_transactions_test.go
> Gitlab Collector: Long running transactions collector and test

- collector/collector.go
- collector/probe.go
I guess the leak was introduced in PR #882 and reported in #898
> Fix a connection leak

- collector/collector.go
- collector/instance.go
> Adjust collector to use separate connection per scrape

- cmd/postgres_exporter/queries.go
This PR tries to fix all error messages, shown on replicas, I've stumbled upon.
It's based on #914, which can be closed with the merge of this PR
> stop logging errors on replicas, fixes #547

- CHANGELOG.md
Sorry, I missed this @SuperQ. After this merges, I'll push the tag.
> Fix version header in changelog
